name: argocd
namespace: argocd
syncWave: "-10"

chart:
  repoURL: https://argoproj.github.io/argo-helm
  name: argo-cd
  version: 9.1.3

helmValues:
  configs:
    params:
      server.insecure: "true"

  server:
    httproute:
      enabled: true
      parentRefs:
        - name: agentgateway
          namespace: kgateway-system
      hostnames:
        - argocd.tmdev.pl