name: servarr
namespace: media

chart:
  repoURL: https://charts.kubito.dev
  name: servarr
  version: 1.2.2

helmValues:
  qbittorrent:
    enabled: true
    image:
      repository: ghcr.io/linuxserver/qbittorrent
      pullPolicy: IfNotPresent
      tag: 5.1.2
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      path: config
      storageClass: longhorn
      size: 1Gi

  prowlarr:
    enabled: true
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 1Gi

  sonarr:
    enabled: true
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      path: config
      storageClass: longhorn
      size: 5Gi

  radarr:
    enabled: false
    image:
      tag: "5.14.0"
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      path: config
      storageClass: longhorn
      size: 5Gi

  bazarr:
    enabled: true
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      path: config
      storageClass: longhorn
      size: 5Gi
  
  jellyfin:
    enabled: true
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 10Gi
      media:
        enabled: true
        existingClaim: media-nfs-pvc

  jellyseerr:
    enabled: false
  lidarr:
    enabled: false
  flaresolverr:
    enabled: false
  cleanuparr:
    enabled: false
  