name: servarr
namespace: media

chart:
  repoURL: https://charts.kubito.dev
  name: servarr
  version: 1.2.2

helmValues:
  jellyfin:
    enabled: true
    extraEnvVars:
      - name: TZ
        value: "Europe/Warsaw"
      - name: JELLYFIN_CACHE_DIR
        value: "/tmp/jellyfin-cache"
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 50Gi
      media:
        enabled: true
        existingClaim: media-nfs-pvc

  qbittorrent:
    enabled: true
    image:
      repository: ghcr.io/linuxserver/qbittorrent
      pullPolicy: IfNotPresent
      tag: 5.1.2
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 2Gi

  prowlarr:
    enabled: true
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 2Gi

  sonarr:
    enabled: true
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 2Gi

  radarr:
    enabled: true
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 2Gi

  bazarr:
    enabled: true
    env:
      TZ: "Europe/Warsaw"
    persistence:
      enabled: true
      storageClass: longhorn
      size: 2Gi
  
  
  jellyseerr:
    enabled: false
  lidarr:
    enabled: false
  flaresolverr:
    enabled: false
  cleanuparr:
    enabled: false
  