name: sonarr
namespace: media

chart:
  repoURL: https://charts.pree.dev
  name: sonarr
  version: 1.11.1

helmValues:
  image:
    repository: ghcr.io/home-operations/sonarr
    pullPolicy: IfNotPresent
    tag: 4.0.16

  env:
    TZ: Europe/Warsaw

  persistence:
    config:
      enabled: true
      storageClass: longhorn
      size: 5Gi
      retain: true
    downloads:
      enabled: true
      existingClaim: media-nfs-pvc
      mountPath: /downloads
      subPath: downloads
    media:
      enabled: true
      existingClaim: media-nfs-pvc
      mountPath: /media
      subPath: tv

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000