name: local-path-exporter
namespace: monitoring
syncWave: "-5"

chart:
  repoURL: https://tmusial99.github.io/local-path-exporter
  name: local-path-exporter
  version: 0.1.0

helmValues:
  config:
    metricTemplate: "pvc-*_{pvc_namespace}_{pvc_name}"
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack